user_token: YTkyMmNiNTktN2ZjNS00ZTRmLWI2MTMtOGRhOGNiMTU4ODVkXzU1OTA=

session:
  key: key_to_generate
admin:
  email: admin@admin.com
  password: admin
bot:
  token: access_token
  group_id: 222306604


